# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 18:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ripens', models.CharField(max_length=255)),
                ('origin_date', models.CharField(max_length=255)),
                ('is_pollen_sterile', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FruitUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('use', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraftedTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('on_hand', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('latitude', models.CharField(max_length=255, null=True)),
                ('longitude', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('on_hand', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rootstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('max_height', models.PositiveIntegerField()),
                ('max_width', models.PositiveIntegerField()),
                ('dwarfing', models.CharField(choices=[('Dw', 'Dwarf'), ('Sd', 'Semi-Dwarf'), ('Fs', 'Full Size')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RootstockInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('on_hand', models.PositiveIntegerField()),
                ('rootstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rootstock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('on_hand', models.PositiveIntegerField()),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Cultivar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rootstock',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Species'),
        ),
        migrations.AddField(
            model_name='graftedtree',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pot'),
        ),
        migrations.AddField(
            model_name='graftedtree',
            name='rootstock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rootstock'),
        ),
        migrations.AddField(
            model_name='graftedtree',
            name='scion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cultivar'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Location'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='sources',
            field=models.ManyToManyField(to='core.ScionSource'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Species'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='uses',
            field=models.ManyToManyField(to='core.FruitUse'),
        ),
        migrations.AlterUniqueTogether(
            name='rootstock',
            unique_together=set([('species', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='cultivar',
            unique_together=set([('species', 'name')]),
        ),
    ]
