# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160403_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, to='core.ScionSource'),
        ),
    ]
