# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160403_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivar',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='origin_date',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
    ]
