# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_address_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Max Draughn', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
