# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_address_customer_order'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurserylabelorder',
            name='customer_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nurserylabelorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
    ]
