# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20160406_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurserylabelorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
